# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-google_analytics}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason L Perry"]
  s.date = %q{2010-04-27}
  s.description = %q{Embeds GA tracking code in the bottom of HTML documents}
  s.email = %q{jasper@ambethia.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rack/google_analytics.rb",
     "lib/rack/google_analytics/body.rb",
     "lib/rack/google_analytics/config.rb",
     "lib/rack/google_analytics/dispatcher.rb",
     "lib/rack/google_analytics/image.rb",
     "rack-google_analytics.gemspec",
     "test/rack/google_analytics_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/ambethia/rack-google_analytics}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Google Analytics for Rack applications}
  s.test_files = [
    "test/rack/google_analytics_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 0.9.1"])
      s.add_runtime_dependency(%q<curb>, [">= 0.7.1"])
      s.add_development_dependency(%q<test-unit>, [">= 2.0.7"])
    else
      s.add_dependency(%q<rack>, [">= 0.9.1"])
      s.add_dependency(%q<curb>, [">= 0.7.1"])
      s.add_dependency(%q<test-unit>, [">= 2.0.7"])
    end
  else
    s.add_dependency(%q<rack>, [">= 0.9.1"])
    s.add_dependency(%q<curb>, [">= 0.7.1"])
    s.add_dependency(%q<test-unit>, [">= 2.0.7"])
  end
end

